[project]
name = "eapproval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.11",
    "gunicorn>=25.1.0",
    "python-dotenv>=1.2.1",
]
